import 'package:get/get.dart';
import 'package:newshub/app/controllers/id_controller.dart';
import 'package:newshub/app/routes/app_routes.dart';
import 'package:newshub/app/widget/blur_loading_widget.dart';
import 'package:newshub/sqflite_db/controller/article_controller.dart';
import 'package:newshub/sqflite_db/controller/follow_controller.dart';
import 'package:newshub/sqflite_db/model/user_model.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../service/auth_service.dart';

class AuthController extends GetxController {
  var isLoading = false.obs;
  var error = ''.obs;

  final AuthService _service = AuthService();

  /// Login method
  Future<UserModel?> login({
    required String email,
    required String password,
  }) async {
    isLoading.value = true;
    error.value = '';

    try {
      // Call service to get user
      final user = await _service.login(email, password);

      if (user == null) {
        error.value = 'Invalid email or password';
      } else {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setInt('userId', user.userId ?? 0);
        await prefs.setString('name', user.name);
        await prefs.setString('email', user.email);

        BlurLoadingWidget.show();
        await Future.delayed(const Duration(seconds: 2));
        BlurLoadingWidget.hide();

        Get.offNamed(Routes.BOTTOM_NAV);

        // ✅ Update IdController immediately
        final idController = Get.find<IdController>();
        idController.currentUserId.value = user.userId ?? 0;

        // Optional: clear dependent controllers
        final articleController = Get.find<ArticleController>();
        final followController = Get.find<FollowController>();

        articleController.articles.clear();
        articleController.fetchArticles();

        followController.followingAuthors.clear();
        followController.loadAllFollowStatus();
      }

      return user;
    } catch (e) {
      error.value = 'Login failed: $e';
      return null;
    } finally {
      isLoading.value = false;
    }
  }

  /// Register method
  Future<UserModel?> register({
    required String name,
    required String email,
    required String password,
  }) async {
    isLoading.value = true;
    error.value = '';

    try {
      // Check if email already exists
      final exists = await _service.getUserByEmail(email);
      if (exists != null) {
        error.value = 'Email already exists';
        return null;
      }

      // Step 1: Create new user (userId will be auto-generated by DB)
      final newUser = UserModel(
        userId: null,
        name: name,
        email: email,
        password: password,
        createdAt: '',
        updatedAt: '',
      );

      // Step 2: Insert user → returns new ID
      final userId = await _service.insertUser(newUser);
      newUser.userId = userId;

      // Step 3: Automatically set profileImage = https://i.pravatar.cc/150?img={userId}
      newUser.profileImage = "https://i.pravatar.cc/150?img=$userId";

      // Step 4: Update user (save the profile image)
      await _service.updateUser(newUser);

      print("-" * 80);
      print("User ID: ${newUser.userId}");
      print("Profile Image: ${newUser.profileImage}");
      print("-" * 80);

      // Step 5: Save user info to SharedPreferences
      final prefs = await SharedPreferences.getInstance();
      await prefs.setInt('userId', newUser.userId ?? 0);
      await prefs.setString('name', newUser.name);
      await prefs.setString('email', newUser.email);
      await prefs.setString('profileImage', newUser.profileImage ?? '');

      // Loading animation
      BlurLoadingWidget.show();
      await Future.delayed(const Duration(seconds: 2));
      BlurLoadingWidget.hide();

      // Navigate to Login
      Get.offAllNamed(Routes.LOGIN);

      return newUser;
    } catch (e) {
      error.value = 'Registration failed: $e';
      return null;
    } finally {
      isLoading.value = false;
    }
  }

  /// Check if user is already logged in
  Future<bool> isLoggedIn() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.containsKey('userId');
  }

  /// Logout user
  Future<void> logout() async {
    try {
      BlurLoadingWidget.show();
      await Future.delayed(const Duration(seconds: 2));

      // Clear shared preferences
      final prefs = await SharedPreferences.getInstance();
      await prefs.clear();

      // Reset controllers
      final idController = Get.find<IdController>();
      final articleController = Get.find<ArticleController>();
      final followController = Get.find<FollowController>();

      idController.currentUserId.value = 0;
      articleController.articles.clear();
      followController.followingAuthors.clear();
      // followController.isFollowing.value = false;

      // Navigate to login screen
      Get.offAllNamed(Routes.LOGIN);

      BlurLoadingWidget.hide();
    } catch (e) {
      print("Logout error: $e");
    }
  }

}