const Map<String, String> enUs = {
  // Settings
  'change_password_subtitle': 'Change your account password',
  'change_password_coming_soon': 'Change password feature coming soon',
  'manage_your_privacy_settings': 'Manage your privacy settings',
  'privacy_settings_coming_soon': 'Privacy settings feature coming soon',
  'delete_account_subtitle': 'Permanently delete your account',
  'delete_account_confirmation':
      'Are you sure you want to delete your account? This action cannot be undone.',
  'account_deleted': 'Account Deleted',
  'account_deleted_message': 'Your account has been deleted',
  'feature': 'Feature',

  // Common
  'app_name': 'eNews',
  'welcome': 'Welcome',
  'email': 'Email',
  'display_name': 'Display Name',
  'password': 'Password',
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'search': 'Search',
  'settings': 'Settings',
  'preferences': 'Preferences',
  'push_notifications': 'Push Notifications',
  'receive_breaking_news': 'Receive breaking news alerts',
  'email_notifications': 'Email Notifications',
  'daily_news_digest': 'Daily news digest via email',
  'dark_mode': 'Dark Mode',
  'enable_dark_theme': 'Enable dark theme',
  'account': 'Account',
  'change_password': 'Change Password',
  'privacy_settings': 'Privacy Settings',
  'delete_account': 'Delete Account',
  'profile': 'Profile',
  'about': 'About',
  'about_help': 'About & Help',
  'refreshed': 'Refreshed',
  'removed': 'Removed',

  //login
  'wellcome_back':'Welcome Back',
  'sign_in_to_continue':'Sign in to continue',

    //logout
  'create_account':'Create Account',
  'sign_up_to_get_started':'Sign Up to Get Started',

      //forgotpass
  'enter_your_email_address_and_we\'ll_send_you_a_link_to_reset_your_password':'Enter your email address and we\'ll send you a link to reset your password',
  'send_reset_link':'Send Reset Link',

  // Auth
  'login_title': 'Login to your account',
  'register_title': 'Create new account',
  'forgot_password': 'Forgot Password?',
  'dont_have_account': 'Don\'t have an account?',
  'already_have_account': 'Already have an account?',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'name': 'Full Name',
  'confirm_password': 'Confirm Password',
  'welcome_back':'Welcome back',
  'null':'',
  'password_must_be_at_least_6_characters': 'Password must be at least 6 characters',
  'email_already_registered._please_login_instead.': 'Email already registered. Please login instead.',
  'account_created_successfully!_please_login.': 'Account created successfully! Please login.',
  'name_must_be_at_least_3_characters': 'Name must be at least 3 characters',
  'please_fill_in_all_fields': 'Please fill in all fields',
  'please_enter_a_valid_email_address': 'Please enter a valid email address',
  'please_enter_your_email_and_password': 'Please enter your email and password',
  'please_enter_your_email_address': 'Please enter your email address',
  'password_reset_link_sent_to_your_email': 'Password reset link sent to your email',
  'incorrect_password': 'Incorrect password. Please try again.',
  'account_not_found': 'Account not found. Please register first.',


  // Navigation
  'home': 'Home',
  'category': 'Category',
  'dashboard': 'Dashboard',
  'saved': 'Saved',

  // Dashboard
  'overview': 'Overview',
  'views': 'Views',
  'visits': 'Visits',
  'new_users': 'New Users',
  'active_users': 'Active Users',
  'users': 'Users',
  'projects': 'Projects',
  'operating_status': 'Operating Status',
  'device_traffic': 'Device Traffic',
  'create_new_category': 'Create New Category',
  'admin':'Admin',
  'edit_category':'Edit Category',
  'delete_category':'Delete Category',
  'media':'Media',
  'color':'Color',
  'description':'Description',
  'tag':'Tag',
  'video':'Video',
  'image':'Image',
  'news_feed':'News Feed',
  'article':'Article',
  'coming_soon':'Coming soon',
  'delete_category_confirmation':'Are you sure you want to delete',
  'create_post':'Create Post',
  'post':'Post',
  'edit_info':'Edit Info',
  'change_cover':'Change Cover',
  'edit_cover':'Edit Cover',
  'title':'Title',
  'interested_headlines_for_more_people_to_see':'Interested headlines for more people to see',
  'topics':'Topics',
  'add':'Add',
  'admin_dashboard':'Admin Dashboard',

  // Home
  'following': 'Following',
  'popular': 'Popular',
  'news': 'News',
  'sports': 'Sports',
  'entertainment': 'Entertainment',
  'technology': 'Technology',
  'latest_posts': 'Latest Posts',
  'see_all': 'See All',
  'like': 'Like',
  'comment': 'Comment',
  'report': 'Report',
  'edit_this_post': 'Edit this Post',
  'add_to_favorite_list': 'Add to Favorites List',
  'remove_this_post_permanently': 'Remove this post permanently',
  'report_inappropriate_content': 'Report Inappropriate Content',
  'write_a_comment': 'Write a comment...',
  'share_video': 'Share Video',
  'copy_link': 'Copy Link',
  'share_to_other_apps': 'Share to other apps',
  'send_in_message': 'Send in Message',
  'just_now': 'Just now',
  'retry': 'Retry',
  'no_articles': 'No articles available',
  'videos_label': 'Videos',
  'hot_news': 'Hot News',
  'no_videos': 'No videos available',
  'hot': 'HOT',
  'all': 'All',
  'phone': 'Phone',
  'or_continue_with': 'or continue with',
  'continue_with': 'Continue with',
  'sign_up_with': 'Sign up with',

  // Profile / Settings additional
  'only_regular_users_can_edit_profile': 'Only regular users can edit profile',
  'choose_avatar': 'Choose avatar',
  'profile_updated': 'Profile updated',
  'failed_to_save_profile': 'Failed to save profile',
  'theme': 'Theme',
  'light_mode': 'Light Mode',
  'language': 'Language',
  'about_app': 'About App',
  'help_support': 'Help & Support',
  'help_support_coming_soon': 'Help & Support coming soon',
  'close': 'Close',
  'logged_out': 'Logged Out',
  'logged_out_message': 'You have been successfully logged out',
  'no_hot_news': 'No hot news available',

  //edit
  'post_updated_successfully' : 'Post updated successfully',
  'post_created_successfully' : 'Post created successfully',
  'title_is_required' : 'Title is required',
  'enter_topic' : 'Enter topic (with #)',
  'add_topic' : 'Add Topic',
  'topic' : 'Topic',

  // Profile
  'edit_profile': 'Edit Profile',
  'my_bookmarks': 'My Bookmarks',
  'notification': 'Notification',
  'setting': 'Setting',
  'logout_confirm': 'Are you sure you want to logout?',
  'Logout': 'Logout',
  'Cancel': 'Cancel',
  'saved_articles': 'Saved Articles',
  'no_saved_articles_yet': 'No saved articles yet',
  'articles_you_save_will_appear_here': 'Articles you save will appear here',
  

  // Search
  'search_news': 'Search news...',
  'recent_searches': 'Recent Searches',
  'trending_topics': 'Trending Topics',
  'trending_videos': 'Trending Videos',

  // Search additions
  'clear_filters': 'Clear Filters',
  'no_articles_for': 'No articles found for "{query}"',
  'sort_latest': 'Latest',
  'sort_popular': 'Popular',
  'sort_oldest': 'Oldest',
  'articles_found': 'articles found',

  // Article
  'read_more': 'Read More',
  'min_read': 'min read',
  'bookmark': 'Bookmark',
  'share': 'Share',
  'bookmarks': 'Bookmarks',
  'no_bookmarks_yet': 'No bookmarks yet',
  'article_removed_from_bookmarks': 'Article removed from bookmarks',
  'user':'User',
  'manage_users':'Manage Users',
  'organizer':'Organizer',
  'add_article':'Add Article',
  'create_category':'Create Category',
  'parent_category':'Parent Category',
  'category_name':'Category Name',
  'slug':'Slug',
  'manage_categories':'Manage Categories',
  'add_category':'Add Category',
  'save_category':'Save Category',
  'update_category':'Update Category',
  'reports_analytics':'Reports & Analytics',
  'article_statistics':'Article Statistics',
  'total_likes':'Total Likes',
  'total_comments':'Total Comments',
  'total_shares':'Total Shares',
  'total_bookmarks':'Total Bookmarks',
  'published':'Published',
  'drafts':'Drafts',
  'manage_articles':'Manage Articles',
  // 'description':'Description',
  // 'edit_category':'Edit Category',

  // Notifications
  'notifications': 'Notifications',
  'mark_all_read': 'Mark all as read',
  'no_notifications': 'No notifications',

  // Language
  'select_language': 'Select Language',
  'english': 'English',
  'khmer': 'ភាសាខ្មែរ',

  // Errors
  'error': 'Error',
  'success': 'Success',
  'warning': 'Warning',
  'info': 'Info',
  'invalid_email': 'Invalid email address',
  'invalid_password': 'Password must be at least 6 characters',
  'passwords_dont_match': 'Passwords don\'t match',
  'all_fields_required': 'All fields are required',
  'login_failed': 'Login failed. Please check your credentials',
  'registration_failed': 'Registration failed. Please try again',
  'network_error': 'Network error. Please check your connection',
  // Admin / Dashboard & Form
  'recent_users': 'Recent Users',
  'recent_articles': 'Recent Articles',
  'total_users': 'Total Users',
  'total_articles': 'Total Articles',
  'categories': 'Categories',
  'tags': 'Tags',
  'no_recent_articles': 'No recent articles',
  'no_recent_users': 'No recent users',
  'create_user': 'Create User',
  'profile_image': 'Profile Image',
  'tap_to_add': 'Tap to add',
  'update_user': 'Update User',
  'please_enter_display_name': 'Please enter display name',
  'email_required': 'Email is required',
  'password_required': 'Password is required',
  'display_name_required': 'Display name is required',
  'account_status': 'Account Status',
  'active': 'Active',
  'inactive': 'Inactive',
  'select_role': 'Select Role',
  'save_user': 'Save User',
  'role_required': 'Role is required',
  'articles': 'Articles',
  'reports': 'Reports',
  'admin_followers':'Admin Followers',
  'organizer_followers':'Organizer Followers',
  'total_views':'Total Views',
  'pubilished':'Published',
  'draft':'Draft',
  'archived':'Archived',
  'filter_by_category':'Filter by Category',
  'select_category':'Select Category',
  'clear':'Clear',
  'apply': 'Apply',
  'official_account':'Official Account',
  'news_organizer':'News Organizer',
  'comments':'Comments',
  'block_this_user':'Block this user',
  'are_you_sure_you_want_to_block_this_user':'Are you sure you want to block this user?',
  'about_this_article':'About this article',
  'organization_dashboard':'Organization Dashboard',
  'manage_articles_team':'Manage Articles Team',
  'view_team':'View Team',
  'quick_actions':'Quick Actions',
  'team_members':'Team Members',
  'total_team_members':'Total Team Members',
  'actions':'Actions',
  'search_articles':'Search articles...',
  'no_articles_found':'No articles found',
  'create_article':'Create Article',
  'delete_article':'Delete Article',
  'delete_article_confirmation':'Are you sure you want to delete "{title}"?',
  'article_deleted_successfully':'Article deleted successfully',
  'failed_to_delete_article':'Failed to delete article',
  'untitled':'Untitled',
  'total_members':'Total Members',
  
  // User Detail Screen
  'user_details': 'User Details',
  'user_not_found': 'User not found',
  'account_information': 'Account Information',
  'additional_information': 'Additional Information',
  'user_id': 'User ID',
  'member_since': 'Member Since',
  'view_only_notice': 'This is a view-only screen. You cannot edit, update, or delete user information from here.',
  'administrator': 'Administrator',
  'organization': 'Organization',
  'banned': 'Banned',
  'subcategories': 'Subcategories',
  'favorite': 'Favorite',
  'forward': 'Forward',
  
  // Months
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'may': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'november': 'November',
  'december': 'December',

  // Privacy Settings
  'profile_visibility': 'Profile Visibility',
  'show_profile_picture': 'Show Profile Picture',
  'others_can_see_profile_picture': 'Others can see your profile picture',
  'show_email': 'Show Email',
  'display_email_on_profile': 'Display email on your profile',
  'show_phone': 'Show Phone Number',
  'display_phone_on_profile': 'Display phone number on your profile',
  'interactions': 'Interactions',
  'allow_tagging': 'Allow Tagging',
  'others_can_tag_you': 'Others can tag you in posts',
  'show_online_status': 'Show Online Status',
  'display_when_active': 'Display when you\'re active',
  'allow_messaging': 'Allow Messaging',
  'receive_messages_from_others': 'Receive messages from others',
  'notification_preferences': 'Notification Preferences',
  'receive_push_notifications': 'Receive push notifications',
  'receive_email_updates': 'Receive email updates',
  'data_privacy': 'Data & Privacy',
  'data_collection': 'Data Collection',
  'allow_data_collection_for_improvement': 'Allow data collection for app improvement',
  'personalization': 'Personalization',
  'personalize_content_based_on_activity': 'Personalize content based on your activity',
  'delete_my_account': 'Delete My Account',
  'delete_account_warning': 'Warning: This will permanently delete your account and all associated data. This action cannot be undone.',
  'privacy_settings_saved': 'Privacy settings saved',

  // About App
  'version': 'Version',
  'app_description': 'Stay informed with the latest news from Cambodia and around the world. Your trusted source for breaking news, in-depth analysis, and trending stories.',
  'developer': 'Developer',
  'contact_email': 'Contact Email',
  'website': 'Website',
  'location': 'Location',
  'rate_app': 'Rate App',
  'share_app': 'Share App',
  'terms_of_service': 'Terms of Service',
  'privacy_policy': 'Privacy Policy',
  'all_rights_reserved': 'All rights reserved',
  'terms_content': 'Terms of Service\n\n1. Acceptance of Terms\nBy using this app, you agree to these terms.\n\n2. User Conduct\nYou agree to use the app responsibly and not engage in any harmful activities.\n\n3. Content\nAll content is provided for informational purposes.\n\n4. Changes to Terms\nWe reserve the right to modify these terms at any time.',
  'privacy_policy_content': 'Privacy Policy\n\n1. Information Collection\nWe collect information to provide better services.\n\n2. Information Usage\nYour data is used to improve your experience.\n\n3. Information Sharing\nWe do not sell your personal information.\n\n4. Security\nWe implement security measures to protect your data.\n\n5. Contact\nFor privacy concerns, contact us at support@enews.com',

  // Help & Support
  'need_help': 'Need Help?',
  'we_are_here_to_help': 'We\'re here to help you 24/7',
  'contact_us': 'Contact Us',
  'email_support': 'Email Support',
  'phone_support': 'Phone Support',
  'live_chat': 'Live Chat',
  'available_24_7': 'Available 24/7',
  'frequently_asked_questions': 'Frequently Asked Questions',
  'send_feedback': 'Send Feedback',
  'feedback_placeholder': 'Tell us what you think...',
  'feedback_sent_successfully': 'Feedback sent successfully!',
  'contact': 'Contact',
  
  // FAQ Questions
  'how_to_create_account': 'How do I create an account?',
  'how_to_create_account_answer': 'Tap on the "Register" button on the login screen. Fill in your details including email, display name, and password. Verify your email and you\'re ready to go!',
  'how_to_reset_password': 'How do I reset my password?',
  'how_to_reset_password_answer': 'On the login screen, tap "Forgot Password". Enter your registered email and we\'ll send you a password reset link.',
  'how_to_post_article': 'How do I post an article?',
  'how_to_post_article_answer': 'Navigate to the home screen and tap the "+" button. Choose "Article" and fill in the title, content, and select a category. Tap "Publish" when ready.',
  'how_to_save_article': 'How do I save articles for later?',
  'how_to_save_article_answer': 'Tap the bookmark icon on any article to save it. Access all your saved articles from the "Saved" tab in the bottom navigation.',
  'how_to_report_content': 'How do I report inappropriate content?',
  'how_to_report_content_answer': 'Tap the three-dot menu on any post and select "Report". Choose a reason and submit. Our team will review it within 24 hours.',
  'how_to_delete_account': 'How do I delete my account?',
  'how_to_delete_account_answer': 'Go to Profile > Privacy Settings > Delete My Account. Confirm your decision. Note: This action is permanent and cannot be undone.',
  
  // Change Password & Delete Account
  'current_password': 'Current Password',
  'new_password': 'New Password',
  'confirm_new_password': 'Confirm New Password',
  'enter_password_to_confirm': 'Enter your password to confirm',
  'please_enter_password': 'Please enter your password',
  'password_min_length': 'Password must be at least 6 characters',
  'passwords_do_not_match': 'Passwords do not match',

  'send': 'Send',
};
