const Map<String, String> enUs = {
  // Settings
  'change_password_subtitle': 'Change your account password',
  'change_password_coming_soon': 'Change password feature coming soon',
  'manage_your_privacy_settings': 'Manage your privacy settings',
  'privacy_settings_coming_soon': 'Privacy settings feature coming soon',
  'delete_account_subtitle': 'Permanently delete your account',
  'delete_account_confirmation':
      'Are you sure you want to delete your account? This action cannot be undone.',
  'account_deleted': 'Account Deleted',
  'account_deleted_message': 'Your account has been deleted',
  'feature': 'Feature',

  // Common
  'app_name': 'eNews',
  'welcome': 'Welcome',
  'email': 'Email',
  'display_name': 'Display Name',
  'password': 'Password',
  'login': 'Login',
  'register': 'Register',
  'logout': 'Logout',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'search': 'Search',
  'settings': 'Settings',
  'preferences': 'Preferences',
  'push_notifications': 'Push Notifications',
  'receive_breaking_news': 'Receive breaking news alerts',
  'email_notifications': 'Email Notifications',
  'daily_news_digest': 'Daily news digest via email',
  'dark_mode': 'Dark Mode',
  'enable_dark_theme': 'Enable dark theme',
  'account': 'Account',
  'change_password': 'Change Password',
  'privacy_settings': 'Privacy Settings',
  'delete_account': 'Delete Account',
  'profile': 'Profile',
  'about': 'About',
  'about_help': 'About & Help',
  'refreshed': 'Refreshed',
  'removed': 'Removed',

  //login
  'wellcome_back':'Welcome Back',
  'sign_in_to_continue':'Sign in to continue',

    //logout
  'create_account':'Create Account',
  'sign_up_to_get_started':'Sign Up to Get Started',

      //forgotpass
  'enter_your_email_address_and_we\'ll_send_you_a_link_to_reset_your_password':'Enter your email address and we\'ll send you a link to reset your password',
  'send_reset_link':'Send Reset Link',

  // Auth
  'login_title': 'Login to your account',
  'register_title': 'Create new account',
  'forgot_password': 'Forgot Password?',
  'dont_have_account': 'Don\'t have an account?',
  'already_have_account': 'Already have an account?',
  'sign_in': 'Sign In',
  'sign_up': 'Sign Up',
  'name': 'Full Name',
  'confirm_password': 'Confirm Password',
  'welcome_back':'Welcome back',
  'null':'',
  'password_must_be_at_least_6_characters': 'Password must be at least 6 characters',
  'email_already_registered._please_login_instead.': 'Email already registered. Please login instead.',
  'account_created_successfully!_please_login.': 'Account created successfully! Please login.',
  'name_must_be_at_least_3_characters': 'Name must be at least 3 characters',
  'please_fill_in_all_fields': 'Please fill in all fields',
  'please_enter_a_valid_email_address': 'Please enter a valid email address',
  'please_enter_your_email_and_password': 'Please enter your email and password',
  'please_enter_your_email_address': 'Please enter your email address',
  'password_reset_link_sent_to_your_email': 'Password reset link sent to your email',
  'incorrect_password': 'Incorrect password. Please try again.',
  'account_not_found': 'Account not found. Please register first.',


  // Navigation
  'home': 'Home',
  'category': 'Category',
  'dashboard': 'Dashboard',
  'saved': 'Saved',

  // Dashboard
  'overview': 'Overview',
  'views': 'Views',
  'visits': 'Visits',
  'new_users': 'New Users',
  'active_users': 'Active Users',
  'users': 'Users',
  'projects': 'Projects',
  'operating_status': 'Operating Status',
  'device_traffic': 'Device Traffic',
  'create_new_category': 'Create New Category',
  'admin':'Admin',
  'edit_category':'Edit Category',
  'delete_category':'Delete Category',
  'media':'Media',
  'color':'Color',
  'description':'Description',
  'tag':'Tag',
  'video':'Video',
  'image':'Image',
  'news_feed':'News Feed',
  'article':'Article',
  'coming_soon':'Coming soon',
  'delete_category_confirmation':'Are you sure you want to delete',
  'create_post':'Create Post',
  'post':'Post',
  'edit_info':'Edit Info',
  'change_cover':'Change Cover',
  'edit_cover':'Edit Cover',
  'title':'Title',
  'interested_headlines_for_more_people_to_see':'Interested headlines for more people to see',
  'topics':'Topics',
  'add':'Add',
  'admin_dashboard':'Admin Dashboard',

  // Home
  'following': 'Following',
  'popular': 'Popular',
  'news': 'News',
  'sports': 'Sports',
  'entertainment': 'Entertainment',
  'technology': 'Technology',
  'latest_posts': 'Latest Posts',
  'see_all': 'See All',
  'like': 'Like',
  'comment': 'Comment',
  'report': 'Report',
  'edit_this_post': 'Edit this Post',
  'add_to_favorite_list': 'Add to Favorites List',
  'remove_this_post_permanently': 'Remove this post permanently',
  'report_inappropriate_content': 'Report Inappropriate Content',
  'write_a_comment': 'Write a comment...',
  'share_video': 'Share Video',
  'copy_link': 'Copy Link',
  'share_to_other_apps': 'Share to other apps',
  'send_in_message': 'Send in Message',
  'just_now': 'Just now',
  'retry': 'Retry',
  'no_articles': 'No articles available',
  'videos_label': 'Videos',
  'hot_news': 'Hot News',
  'no_videos': 'No videos available',
  'hot': 'HOT',
  'all': 'All',
  'phone': 'Phone',
  'or_continue_with': 'or continue with',
  'continue_with': 'Continue with',
  'sign_up_with': 'Sign up with',

  // Profile / Settings additional
  'only_regular_users_can_edit_profile': 'Only regular users can edit profile',
  'choose_avatar': 'Choose avatar',
  'profile_updated': 'Profile updated',
  'failed_to_save_profile': 'Failed to save profile',
  'theme': 'Theme',
  'light_mode': 'Light Mode',
  'language': 'Language',
  'about_app': 'About App',
  'help_support': 'Help & Support',
  'help_support_coming_soon': 'Help & Support coming soon',
  'close': 'Close',
  'logged_out': 'Logged Out',
  'logged_out_message': 'You have been successfully logged out',
  'no_hot_news': 'No hot news available',

  //edit
  'post_updated_successfully' : 'Post updated successfully',
  'post_created_successfully' : 'Post created successfully',
  'title_is_required' : 'Title is required',
  'enter_topic' : 'Enter topic (with #)',
  'add_topic' : 'Add Topic',
  'topic' : 'Topic',

  // Profile
  'edit_profile': 'Edit Profile',
  'my_bookmarks': 'My Bookmarks',
  'notification': 'Notification',
  'setting': 'Setting',
  'logout_confirm': 'Are you sure you want to logout?',
  'Logout': 'Logout',
  'Cancel': 'Cancel',
  'saved_articles': 'Saved Articles',
  'no_saved_articles_yet': 'No saved articles yet',
  'articles_you_save_will_appear_here': 'Articles you save will appear here',
  

  // Search
  'search_news': 'Search news...',
  'recent_searches': 'Recent Searches',
  'trending_topics': 'Trending Topics',
  'trending_videos': 'Trending Videos',

  // Search additions
  'clear_filters': 'Clear Filters',
  'no_articles_for': 'No articles found for "{query}"',
  'sort_latest': 'Latest',
  'sort_popular': 'Popular',
  'sort_oldest': 'Oldest',
  'articles_found': 'articles found',

  // Article
  'read_more': 'Read More',
  'min_read': 'min read',
  'bookmark': 'Bookmark',
  'share': 'Share',
  'bookmarks': 'Bookmarks',
  'no_bookmarks_yet': 'No bookmarks yet',
  'article_removed_from_bookmarks': 'Article removed from bookmarks',
  'user':'User',
  'manage_users':'Manage Users',
  'organizer':'Organizer',
  'add_article':'Add Article',
  'create_category':'Create Category',
  'parent_category':'Parent Category',
  'category_name':'Category Name',
  'slug':'Slug',
  'manage_categories':'Manage Categories',
  'add_category':'Add Category',
  'save_category':'Save Category',
  'update_category':'Update Category',
  'reports_analytics':'Reports & Analytics',
  'article_statistics':'Article Statistics',
  'total_likes':'Total Likes',
  'total_comments':'Total Comments',
  'total_shares':'Total Shares',
  'total_bookmarks':'Total Bookmarks',
  'published':'Published',
  'drafts':'Drafts',
  'manage_articles':'Manage Articles',
  // 'description':'Description',
  // 'edit_category':'Edit Category',

  // Notifications
  'notifications': 'Notifications',
  'mark_all_read': 'Mark all as read',
  'no_notifications': 'No notifications',

  // Language
  'select_language': 'Select Language',
  'english': 'English',
  'khmer': 'ភាសាខ្មែរ',

  // Errors
  'error': 'Error',
  'success': 'Success',
  'warning': 'Warning',
  'info': 'Info',
  'invalid_email': 'Invalid email address',
  'invalid_password': 'Password must be at least 6 characters',
  'passwords_dont_match': 'Passwords don\'t match',
  'all_fields_required': 'All fields are required',
  'login_failed': 'Login failed. Please check your credentials',
  'registration_failed': 'Registration failed. Please try again',
  'network_error': 'Network error. Please check your connection',
  // Admin / Dashboard & Form
  'recent_users': 'Recent Users',
  'recent_articles': 'Recent Articles',
  'total_users': 'Total Users',
  'total_articles': 'Total Articles',
  'categories': 'Categories',
  'tags': 'Tags',
  'no_recent_articles': 'No recent articles',
  'no_recent_users': 'No recent users',
  'create_user': 'Create User',
  'profile_image': 'Profile Image',
  'tap_to_add': 'Tap to add',
  'update_user': 'Update User',
  'please_enter_display_name': 'Please enter display name',
  'email_required': 'Email is required',
  'password_required': 'Password is required',
  'display_name_required': 'Display name is required',
  'account_status': 'Account Status',
  'active': 'Active',
  'inactive': 'Inactive',
  'select_role': 'Select Role',
  'save_user': 'Save User',
  'role_required': 'Role is required',
  'articles': 'Articles',
  'reports': 'Reports',
  'admin_followers':'Admin Followers',
  'organizer_followers':'Organizer Followers',
  'total_views':'Total Views',
  'pubilished':'Published',
  'draft':'Draft',
  'archived':'Archived',
  'filter_by_category':'Filter by Category',
  'select_category':'Select Category',
  'clear':'Clear',
  'apply': 'Apply',
  'official_account':'Official Account',
  'news_organizer':'News Organizer',
  'comments':'Comments',
  'block_this_user':'Block this user',
  'are_you_sure_you_want_to_block_this_user':'Are you sure you want to block this user?',
  'about_this_article':'About this article',
  'organization_dashboard':'Organization Dashboard',
  'manage_articles_team':'Manage Articles Team',
  'view_team':'View Team',
  'quick_actions':'Quick Actions',
  'team_members':'Team Members',
  'total_team_members':'Total Team Members',
  'actions':'Actions',
  'search_articles':'Search articles...',
  'no_articles_found':'No articles found',
  'create_article':'Create Article',
  'delete_article':'Delete Article',
  'delete_article_confirmation':'Are you sure you want to delete "{title}"?',
  'article_deleted_successfully':'Article deleted successfully',
  'failed_to_delete_article':'Failed to delete article',
  'untitled':'Untitled',
  'total_members':'Total Members',
};
