const Map<String, String> kmKh = {
  // Settings
  'change_password_subtitle': 'ផ្លាស់ប្តូរលេខសម្ងាត់គណនីរបស់អ្នក',
  'change_password_coming_soon': 'មុខងារផ្លាស់ប្តូរលេខសម្ងាត់នឹងមកដល់ឆាប់ៗនេះ',
  'manage_your_privacy_settings': 'គ្រប់គ្រងការកំណត់ឯកជនភាពរបស់អ្នក',
  'privacy_settings_coming_soon': 'មុខងារការកំណត់ឯកជនភាពនឹងមកដល់ឆាប់ៗនេះ',
  'delete_account_subtitle': 'លុបគណនីរបស់អ្នកជាអចិន្ត្រៃយ៍',
  'delete_account_confirmation': 'តើអ្នកប្រាកដថាចង់លុបគណនីរបស់អ្នកមែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយវិញបានទេ។',
  'account_deleted': 'គណនីត្រូវបានលុប',
  'account_deleted_message': 'គណនីរបស់អ្នកត្រូវបានលុប',
  'feature': 'មុខងារ',

  // Common
  'app_name': 'eNews',
  'welcome': 'សូមស្វាគមន៍',
  'email': 'អ៊ីមែល',
  'display_name': 'ឈ្មោះបង្ហាញ',
  'password': 'លេខសម្ងាត់',
  'login': 'ចូលប្រើ',
  'register': 'ចុះឈ្មោះ',
  'logout': 'ចាកចេញ',
  'save': 'រក្សាទុក',
  'cancel': 'បោះបង់',
  'delete': 'លុប',
  'edit': 'កែប្រែ',
  'search': 'ស្វែងរក',
  'settings': 'ការកំណត់',
  'preferences': 'ចំណូលចិត្ត',
  'push_notifications': 'ការជូនដំណឹងជាមួយនឹងការរំញោច',
  'receive_breaking_news': 'ទទួលបានការជូនដំណឹងពីព័ត៌មានថ្មីៗ',
  'email_notifications': 'ការជូនដំណឹងតាមអ៊ីមែល',
  'daily_news_digest': 'ការជូនដំណឹងប្រចាំថ្ងៃតាមអ៊ីមែល',
  'dark_mode': 'ទម្រង់ងងឹត',
  'enable_dark_theme': 'បើកប្រើប្រាស់ទម្រង់ងងឹត',
  'account': 'គណនី',
  'change_password': 'ប្ដូរលេខសម្ងាត់',
  'privacy_settings': 'ការកំណត់ភាពឯកជន',
  'delete_account': 'លុបគណនី',
  'profile': 'ប្រវត្តិរូប',
  'about': 'អំពី',
  'about_help': 'អំពី និង ជំនួយ',
  'refreshed': 'បានធ្វើបច្ចុប្បន្នភាព',
  'removed': 'បានលុប',

   //login
  'wellcome_back':'ស្វាគមន៍មកកាន់',
  'sign_in_to_continue':'ចូលប្រើដើម្បីបន្ត',

    //logout
  'create_account':'បង្កើតគណនី',
  'sign_up_to_get_started':'ចុះឈ្មោះដើម្បីចាប់ផ្តើម',

      //forgotpass
  'enter_your_email_address_and_we\'ll_send_you_a_link_to_reset_your_password':'បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើរលិខិតទៅកាន់អ្នកដើម្បីកំណត់លេខសម្ងាត់របស់អ្នក',
  'send_reset_link':'ផ្ញើរលិខិតកំណត់លេខសម្ងាត់',

  // Auth
  'login_title': 'ចូលប្រើគណនី',
  'register_title': 'បង្កើតគណនីថ្មី',
  'forgot_password': 'ភ្លេចលេខសម្ងាត់?',
  'dont_have_account': 'មិនទាន់មានគណនី?',
  'already_have_account': 'មានគណនីរួចហើយ?',
  'sign_in': 'ចូលប្រើ',
  'sign_up': 'ចុះឈ្មោះ',
  'name': 'ឈ្មោះពេញ',
  'confirm_password': 'បញ្ជាក់លេខសម្ងាត់',
  'welcome_back':'សូមស្វាគមន៍ត្រឡប់មកកាន់',
  'null':'',
  'password_must_be_at_least_6_characters': 'លេខសម្ងាត់ត្រូវតែមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
  'email_already_registered._please_login_instead.': 'អ៊ីមែលបានចុះឈ្មោះរួចហើយ។ សូមចូលប្រើវិញ។',
  'account_created_successfully!_please_login.': 'គណនីត្រូវបានបង្កើតដោយជោគជ័យ! សូមចូលប្រើ។',
  'name_must_be_at_least_3_characters': 'ឈ្មោះត្រូវតែមានយ៉ាងហោចណាស់ ៣ តួអក្សរ',
  'please_fill_in_all_fields': 'សូមបំពេញទាំងអស់',
  'please_enter_a_valid_email_address': 'សូមបញ្ចូលអ៊ីមែលដែលត្រឹមត្រូវ',
  'please_enter_your_email_and_password': 'សូមបញ្ចូលអ៊ីមែល និង លេខសម្ងាត់របស់អ្នក',
  'please_enter_your_email_address': 'សូមបញ្ចូលអ៊ីមែលរបស់អ្នក',
  'password_reset_link_sent_to_your_email': 'លិខិតកំណត់លេខសម្ងាត់ត្រូវបានផ្ញើទៅអ៊ីមែលរបស់អ្នក',
  'incorrect_password': 'លេខសម្ងាត់មិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។',
  'account_not_found': 'រកមិនឃើញគណនីទេ។ សូមចុះឈ្មោះជាមុន។',

  // Navigation
  'home': 'ទំព័រដើម',
  'category': 'ប្រភេទ',
  'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'saved': 'បានរក្សាទុក',

  // Dashboard
  'overview': 'ទិដ្ឋភាពទូទៅ',
  'views': 'ចំនួនមើល',
  'visits': 'ចំនួនចូលមើល',
  'new_users': 'អ្នកប្រើថ្មី',
  'active_users': 'អ្នកប្រើសកម្ម',
  'users': 'អ្នកប្រើ',
  'projects': 'គម្រោង',
  'operating_status': 'ស្ថានភាពប្រតិបត្តិការ',
  'device_traffic': 'ចរាចរឧបករណ៍', 
  'create_new_category': 'បង្កើតប្រភេទថ្មី',
  'admin':'Admin',
  'edit_category':'កែប្រែប្រភេទ',
  'delete_category':'លុបប្រភេទ',
  'media':'មេឌា',
  'color':'ពណ៌',
  'description':'ការពិពណ៌នា',
  'tag':'ស្លាក',
  'video':'វីដេអូ',
  'image':'រូបភាព',
  'news_feed':'ព័ត៌មាន',
  'article':'អត្ថបទ',
  'coming_soon':'មកដល់ឆាប់ៗនេះ',
  'delete_category_confirmation':'តើអ្នកប្រាកដថាចង់លុប',
  'create_post':'បង្កើតប្រកាស',
  'post':'ប្រកាស',
  'edit_info':'កែប្រែព័ត៌មាន',
  'change_cover':'ប្ដូរពណ៌ផ្ទាំង',
  'edit_cover':'កែប្រែពណ៌ផ្ទាំង',
  'title':'ចំណងជើង',
  'interested_headlines_for_more_people_to_see':'ចំណងជើងដែលគួរឱ្យចាប់អារម្មណ៍សម្រាប់មនុស្សច្រើនមើល',
  'topics':'ប្រធានបទ',
  'add':'បន្ថែម',
  'admin_dashboard':'ផ្ទាំងគ្រប់គ្រងរបស់អ្នកគ្រប់គ្រង',

  //edit
  'post_updated_successfully' : 'ប្រកាសត្រូវបានកែប្រែដោយជោគជ័យ',
  'post_created_successfully' : 'ប្រកាសត្រូវបានបង្កើតដោយជោគជ័យ',
  'title_is_required' : 'ចំណងជើងត្រូវការជាអប្បបរមា',
  'enter_topic' : 'បញ្ចូលប្រធានបទ (ជាមួយ #)',
  'add_topic' : 'បន្ថែមប្រធានបទ',
  'topic' : 'ប្រធានបទ',

  // Home
  'following': 'កំពុងតាមដាន',
  'popular': 'ពេញនិយម',
  'news': 'ព័ត៌មាន',
  'sports': 'កីឡា',
  'entertainment': 'កម្សាន្ត',
  'technology': 'បច្ចេកវិទ្យា',
  'latest_posts': 'ប្រកាសថ្មីៗ',
  'see_all': 'មើលទាំងអស់',
  'like': 'ចូលចិត្ត',
  'comment': 'មតិយោបល់',
  'report': 'រាយការណ៍',
  'edit_this_post': 'កែប្រែប្រកាសនេះ',
  'add_to_favorite_list': 'បន្ថែមទៅបញ្ជីចូលចិត្ត',
  'remove_this_post_permanently': 'លុបប្រកាសនេះយ៉ាងស្ថាពរ',
  'report_inappropriate_content': 'រាយការណ៍មាតិកាដែលមិនសមរម្យ',
  'write_a_comment': 'សរសេរមតិយោបល់...',
  'share_video': 'ចែករំលែកវីដេអូ',
  'copy_link': 'ចម្លងតំណភ្ជាប់',
  'share_to_other_apps': 'ចែករំលែកទៅកម្មវិធីផ្សេងទៀត',
  'send_in_message': 'ផ្ញើក្នុងសារ',
  'just_now': 'ឥឡូវនេះ',
  'retry': 'ព្យាយាមម្តងទៀត',
  'no_articles': 'គ្មានអត្ថបទ',
  'videos_label': 'វីដេអូ',
  'hot_news': 'ព័ត៌មានថ្មីៗ',
  'no_videos': 'គ្មានវីដេអូ',
  'hot': 'ក្តៅ',
  'all': 'ទាំងអស់',
  'phone': 'ទូរស័ព្ទ',
  'or_continue_with': 'ឬបន្តជាមួយ',
  'continue_with': 'បន្តជាមួយ',
  'sign_up_with': 'ចុះឈ្មោះជាមួយ',

  // Profile / Settings additional
  'only_regular_users_can_edit_profile': 'តែ​អ្នក​ប្រើដែលជាធម្មតា​អាចកែប្រែប្រវត្តិរូបបាន',
  'choose_avatar': 'ជ្រើសរើសរូបតំណាង',
  'profile_updated': 'ប្រវត្តិរូបត្រូវបានធ្វើបច្ចុប្បន្នភាព',
  'failed_to_save_profile': 'បរាជ័យក្នុងការរក្សាទុកប្រវត្តិរូប',
  'theme': 'ទម្រង់',
  'light_mode': 'ទម្រង់ពន្លឺ',
  'language': 'ភាសា',
  'about_app': 'អំពីកម្មវិធី',
  'help_support': 'ជំនួយ និង គាំទ្រ',
  'help_support_coming_soon': 'ជំនួយ និងគាំទ្រនឹងមកដល់ឆាប់ៗនេះ',
  'close': 'បិទ',
  'logged_out': 'បានចាកចេញ',
  'logged_out_message': 'អ្នកបានចាកចេញដោយជោគជ័យ',
  'no_hot_news': 'មិនមានព័ត៌មានថ្ម្មីៗ',

  // Profile
  'edit_profile': 'កែប្រវត្តិរូប',
  'my_bookmarks': 'កំណត់សម្គាល់របស់ខ្ញុំ',
  'notification': 'ការជូនដំណឹង',
  'setting': 'ការកំណត់',
  'logout_confirm': 'តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ?',
  'Logout': 'ចាកចេញ',
  'Cancel': 'បោះបង់',
  'saved_articles': 'អត្ថបទដែលបានរក្សាទុក',
  'no_saved_articles_yet': 'មិនទាន់មានអត្ថបទដែលបានរក្សាទុក',
  'articles_you_save_will_appear_here': 'អត្ថបទដែលអ្នកបានរក្សាទុកនឹងបង្ហាញនៅទីនេះ',

  // Search
  'search_news': 'ស្វែងរកព័ត៌មាន...',
  'recent_searches': 'ការស្វែងរកថ្មីៗ',
  'trending_topics': 'ប្រធានបទពេញនិយម',
  'trending_videos': 'វីដេអូពេញនិយម',

  // Search additions
  'clear_filters': 'លុបតម្រុយ',
  'no_articles_for': 'រកមិនឃើញអត្ថបទសម្រាប់់ទេ​',
  'sort_latest': 'អត្ថបទថ្មី',
  'sort_popular': 'ពេញនិយម',
  'sort_oldest': 'អត្ថបទចាស់',
  'articles_found': 'អត្ថបទ ត្រូវបានរកឃើញ',

  // Article
  'read_more': 'អានបន្ថែម',
  'min_read': 'នាទីអាន',
  'bookmark': 'រក្សាទុក',
  'share': 'ចែករំលែក',
  'bookmarks': 'ទុករក្សា',
  'no_bookmarks_yet': 'មិនទាន់មានការរក្សាទុក',
  'article_removed_from_bookmarks': 'លុបអត្ថបទចេញពីការរក្សាទុក',
  'user':'អ្នកប្រើ',
  'manage_users':'គ្រប់គ្រងអ្នកប្រើ',
  'organizer':'ស្ថាប័នព័ត៌មាន',
  'add_article':'បន្ថែមអត្ថបទ',
  'create_category':'បង្កើតប្រភេទ',
  'parent_category':'ប្រភេទមេ',
  'category_name':'ឈ្មោះប្រភេទ',
  'slug':'ស្លក់',
  'manage_categories':'គ្រប់គ្រងប្រភេទ',
  'add_category':'បន្ថែមប្រភេទ',
  'save_category':'រក្សាទុកប្រភេទ',
  'update_category':'ធ្វើបច្ចុប្បន្នភាពប្រភេទ',
  'reports_analytics':'របាយការណ៍ និង វិភាគ',
  'article_statistics':'ស្ថិតិអត្ថបទ',
  'total_likes':'ចូលចិត្តសរុប',
  'total_comments':'មតិយោបល់សរុប',
  'total_shares':'ចែករំលែកសរុប',
  'total_bookmarks':'រក្សាទុកសរុប',
  'published':'បានបោះពុម្ពផ្សាយ',
  'drafts':'សេចក្ដីព្រាង',
  'manage_articles':'គ្រប់គ្រងអត្ថបទ',
  // 'description':'ការពិពណ៌នា',
  // 'edit_category':'កែប្រែប្រភេទ',

  // Notifications
  'notifications': 'ការជូនដំណឹង',
  'mark_all_read': 'សម្គាល់ទាំងអស់ថាបានអាន',
  'no_notifications': 'គ្មានការជូនដំណឹង',

  // Language
  'select_language': 'ជ្រើសរើសភាសា',
  'english': 'English',
  'khmer': 'ភាសាខ្មែរ',

  // Errors
  'error': 'កំហុស',
  'success': 'ជោគជ័យ',
  'warning': 'ការព្រមាន',
  'info': 'ព័ត៌មាន',
  'invalid_email': 'អ៊ីមែលមិនត្រឹមត្រូវ',
  'invalid_password': 'លេខសម្ងាត់ត្រូវតែមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
  'passwords_dont_match': 'លេខសម្ងាត់មិនត្រូវគ្នា',
  'all_fields_required': 'ចាំបាច់បំពេញទាំងអស់',
  'login_failed': 'ការចូលប្រើបានបរាជ័យ។ សូមពិនិត្យមើលព័ត៌មានរបស់អ្នក',
  'registration_failed': 'ការចុះឈ្មោះបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត',
  'network_error': 'កំហុសបណ្តាញ។ សូមពិនិត្យការតភ្ជាប់របស់អ្នក',
  // Admin / Dashboard & Form
  'recent_users': 'អ្នកប្រើថ្មីៗ',
  'recent_articles': 'អត្ថបទថ្មីៗ',
  'total_users': 'ចំនួនអ្នកប្រើសរុប',
  'total_articles': 'ចំនួនអត្ថបទសរុប',
  'categories': 'ប្រភេទ',
  'tags': 'ស្លាក',
  'no_recent_articles': 'គ្មានអត្ថបទថ្មីៗ',
  'no_recent_users': 'គ្មានអ្នកប្រើថ្មីៗ',
  'create_user': 'បង្កើតអ្នកប្រើ',
  'profile_image': 'រូបភាពប្រវត្តិ',
  'tap_to_add': 'ចុចដើម្បីបន្ថែម',
  'update_user': 'កែប្រែអ្នកប្រើ',
  'please_enter_display_name': 'សូមបញ្ចូលឈ្មោះបង្ហាញ',
  'email_required': 'ត្រូវការអ៊ីមែល',
  'password_required': 'ត្រូវការលេខសម្ងាត់',
  'display_name_required': 'ត្រូវការឈ្មោះបង្ហាញ',
  'account_status': 'ស្ថានភាពគណនី',
  'active': 'សកម្ម',
  'inactive': 'មិនសកម្ម',
  'select_role': 'ជ្រើសរើសតួនាទី',
  'save_user': 'រក្សាទុកអ្នកប្រើ',
  'role_required': 'ត្រូវការតួនាទី',
  'articles': 'អត្ថបទ',
  'reports': 'របាយការណ៍',
  'admin_followers':'អ្នកគាំទ្រអ្នកគ្រប់គ្រង',
  'organizer_followers':'អ្នកគាំទ្រស្ថាប័នព័ត៌មាន',
  'total_views':'ចំនួនមើលសរុប',
  'pubilished':'ផ្សាយ',
  'draft':'សេចក្ដីព្រាង',
  'archived':'បានរក្សាទុក',
  'filter_by_category':'តម្រុយតាមប្រភេទ',
  'select_category':'ជ្រើសរើសប្រភេទ',
  'clear':'លុប',
  'apply': 'អនុវត្ត',
  'official_account': 'គណនីផ្លូវការ',
  'news_organizer': 'ស្ថាប័នព័ត៌មាន',
  'comments': 'មតិយោបល់',
  'block_this_user': 'ប្លុកអ្នកប្រើនេះ',
  'are_you_sure_you_want_to_block_this_user': 'តើអ្នកប្រាកដថាចង់ប្លុកអ្នកប្រើនេះ?',
  'about_this_article': 'អំពីអត្ថបទនេះ',
  'organization_dashboard': 'ផ្ទាំងព័ត៌មានស្ថាប័ន',
  'manage_articles_team': 'គ្រប់គ្រងក្រុមអត្ថបទ',
  'view_team': 'មើលក្រុម',
  'quick_actions': 'សកម្មភាពរហ័ស',
  'team_members': 'សមាជិកក្រុម',
  'total_team_members': 'ចំនួនសមាជិកក្រុមសរុប',
  'actions': 'សកម្មភាព',
  'search_articles':'ស្វែងរកអត្ថបទ...',
  'no_articles_found':'រកមិនឃើញអត្ថបទ',
  'create_article':'បង្កើតអត្ថបទ',
  'delete_article':'លុបអត្ថបទ',
  'delete_article_confirmation':'តើអ្នកប្រាកដថាចង់លុប "{title}"?',
  'article_deleted_successfully':'អត្ថបទត្រូវបានលុបដោយជោគជ័យ',
  'failed_to_delete_article':'បរាជ័យក្នុងការលុបអត្ថបទ',
  'untitled':'គ្មានចំណងជើង',
  'total_members':'សមាជិកសរុប',
  
  // User Detail Screen
  'user_details': 'ព័ត៌មានលម្អិតអ្នកប្រើ',
  'user_not_found': 'រកមិនឃើញអ្នកប្រើ',
  'account_information': 'ព័ត៌មានគណនី',
  'additional_information': 'ព័ត៌មានបន្ថែម',
  'user_id': 'លេខសម្គាល់អ្នកប្រើ',
  'member_since': 'សមាជិកតាំងពី',
  'view_only_notice': 'នេះគឺជាទំព័រមើលប៉ុណ្ណោះ។ អ្នកមិនអាចកែប្រែ ធ្វើបច្ចុប្បន្នភាព ឬលុបព័ត៌មានអ្នកប្រើពីទីនេះបានទេ។',
  'administrator': 'អ្នកគ្រប់គ្រង',
  'organization': 'អង្គភាព',
  'banned': 'បានហាមឃាត់',
  'subcategories': 'ប្រភេទរង',
  'favorite': 'ចូលចិត្ត',
  'forward': 'បញ្ជូនបន្ត',
  
  // Months
  'january': 'មករា',
  'february': 'កុម្ភៈ',
  'march': 'មីនា',
  'april': 'មេសា',
  'may': 'ឧសភា',
  'june': 'មិថុនា',
  'july': 'កក្កដា',
  'august': 'សីហា',
  'september': 'កញ្ញា',
  'october': 'តុលា',
  'november': 'វិច្ឆិកា',
  'december': 'ធ្នូ',

  // Privacy Settings
  'profile_visibility': 'ភាពមើលឃើញនៃប្រវត្តិរូប',
  'show_profile_picture': 'បង្ហាញរូបភាពប្រវត្តិរូប',
  'others_can_see_profile_picture': 'អ្នកដទៃអាចមើលរូបភាពប្រវត្តិរូបរបស់អ្នក',
  'show_email': 'បង្ហាញអ៊ីមែល',
  'display_email_on_profile': 'បង្ហាញអ៊ីមែលនៅលើប្រវត្តិរូបរបស់អ្នក',
  'show_phone': 'បង្ហាញលេខទូរសព្ទ',
  'display_phone_on_profile': 'បង្ហាញលេខទូរសព្ទនៅលើប្រវត្តិរូបរបស់អ្នក',
  'interactions': 'អន្តរកម្ម',
  'allow_tagging': 'អនុញ្ញាតឱ្យដាក់ស្លាក',
  'others_can_tag_you': 'អ្នកដទៃអាចដាក់ស្លាកអ្នកក្នុងការប្រកាស',
  'show_online_status': 'បង្ហាញស្ថានភាពអនឡាញ',
  'display_when_active': 'បង្ហាញពេលអ្នកកំពុងសកម្ម',
  'allow_messaging': 'អនុញ្ញាតឱ្យផ្ញើសារ',
  'receive_messages_from_others': 'ទទួលសារពីអ្នកដទៃ',
  'notification_preferences': 'ការកំណត់ការជូនដំណឹង',
  'receive_push_notifications': 'ទទួលការជូនដំណឹងជាមួយនឹងការរំញោច',
  'receive_email_updates': 'ទទួលបច្ចុប្បន្នភាពតាមអ៊ីមែល',
  'data_privacy': 'ទិន្នន័យ និង ភាពឯកជន',
  'data_collection': 'ការប្រមូលទិន្នន័យ',
  'allow_data_collection_for_improvement': 'អនុញ្ញាតឱ្យប្រមូលទិន្នន័យសម្រាប់ការកែលម្អកម្មវិធី',
  'personalization': 'ការធ្វើឱ្យផ្ទាល់ខ្លួន',
  'personalize_content_based_on_activity': 'ធ្វើឱ្យមាតិកាផ្ទាល់ខ្លួនដោយផ្អែកលើសកម្មភាពរបស់អ្នក',
  'delete_my_account': 'លុបគណនីរបស់ខ្ញុំ',
  'delete_account_warning': 'ការព្រមាន: នេះនឹងលុបគណនីរបស់អ្នក និង ទិន្នន័យដែលពាក់ព័ន្ធទាំងអស់ជាអចិន្ត្រៃយ៍។ សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយវិញបានទេ។',
  'privacy_settings_saved': 'បានរក្សាទុកការកំណត់ភាពឯកជន',

  // About App
  'version': 'កំណែ',
  'app_description': 'ទទួលបានព័ត៌មានថ្មីៗពីប្រទេសកម្ពុជា និង ពិភពលោក។ ប្រភពដែលអ្នកទុកចិត្តសម្រាប់ព័ត៌មានថ្មីៗ ការវិភាគស៊ីជម្រៅ និង រឿងរ៉ាវពេញនិយម។',
  'developer': 'អ្នកអភិវឌ្ឍន៍',
  'contact_email': 'អ៊ីមែលទំនាក់ទំនង',
  'website': 'គេហទំព័រ',
  'location': 'ទីតាំង',
  'rate_app': 'វាយតម្លៃកម្មវិធី',
  'share_app': 'ចែករំលែកកម្មវិធី',
  'terms_of_service': 'លក្ខខណ្ឌនៃសេវាកម្ម',
  'privacy_policy': 'គោលការណ៍ភាពឯកជន',
  'all_rights_reserved': 'រក្សាសិទ្ធិគ្រប់យ៉ាង',
  'terms_content': 'លក្ខខណ្ឌនៃសេវាកម្ម\n\n១. ការទទួលយកលក្ខខណ្ឌ\nដោយការប្រើប្រាស់កម្មវិធីនេះ អ្នកយល់ព្រមតាមលក្ខខណ្ឌទាំងនេះ។\n\n២. ការប្រព្រឹត្តរបស់អ្នកប្រើប្រាស់\nអ្នកយល់ព្រមប្រើប្រាស់កម្មវិធីដោយទំនួលខុសត្រូវ និង មិនធ្វើសកម្មភាពបង្កគ្រោះថ្នាក់ណាមួយ។\n\n៣. មាតិកា\nមាតិកាទាំងអស់ត្រូវបានផ្តល់ជូនសម្រាប់គោលបំណងផ្តល់ព័ត៌មាន។\n\n៤. ការផ្លាស់ប្តូរលក្ខខណ្ឌ\nយើងរក្សាសិទ្ធិក្នុងការកែប្រែលក្ខខណ្ឌទាំងនេះគ្រប់ពេល។',
  'privacy_policy_content': 'គោលការណ៍ភាពឯកជន\n\n១. ការប្រមូលព័ត៌មាន\nយើងប្រមូលព័ត៌មានដើម្បីផ្តល់សេវាកម្មកាន់តែល្អ។\n\n២. ការប្រើប្រាស់ព័ត៌មាន\nទិន្នន័យរបស់អ្នកត្រូវបានប្រើដើម្បីកែលម្អបទពិសោធន៍របស់អ្នក។\n\n៣. ការចែករំលែកព័ត៌មាន\nយើងមិនលក់ព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នកទេ។\n\n៤. សន្តិសុខ\nយើងអនុវត្តវិធានការសន្តិសុខដើម្បីការពារទិន្នន័យរបស់អ្នក។\n\n៥. ទំនាក់ទំនង\nសម្រាប់ការព្រួយបារម្ភអំពីភាពឯកជន សូមទាក់ទងមកយើងតាម support@enews.com',

  // Help & Support
  'need_help': 'ត្រូវការជំនួយ?',
  'we_are_here_to_help': 'យើងនៅទីនេះដើម្បីជួយអ្នក ២៤/៧',
  'contact_us': 'ទាក់ទងមកយើង',
  'email_support': 'ជំនួយតាមអ៊ីមែល',
  'phone_support': 'ជំនួយតាមទូរសព្ទ',
  'live_chat': 'ជជែកផ្ទាល់',
  'available_24_7': 'មានសេវា ២៤/៧',
  'frequently_asked_questions': 'សំណួរដែលសួរញឹកញាប់',
  'send_feedback': 'ផ្ញើមតិកែលម្អ',
  'feedback_placeholder': 'ប្រាប់យើងនូវគំនិតរបស់អ្នក...',
  'feedback_sent_successfully': 'បានផ្ញើមតិកែលម្អដោយជោគជ័យ!',
  'contact': 'ទំនាក់ទំនង',
  
  // FAQ Questions
  'how_to_create_account': 'តើខ្ញុំបង្កើតគណនីយ៉ាងដូចម្តេច?',
  'how_to_create_account_answer': 'ចុចលើប៊ូតុង "ចុះឈ្មោះ" នៅលើអេក្រង់ចូលប្រើ។ បំពេញព័ត៌មានរបស់អ្នករួមមាន អ៊ីមែល ឈ្មោះបង្ហាញ និង លេខសម្ងាត់។ ផ្ទៀងផ្ទាត់អ៊ីមែលរបស់អ្នក ហើយអ្នករួចរាល់ហើយ!',
  'how_to_reset_password': 'តើខ្ញុំកំណត់លេខសម្ងាត់ឡើងវិញយ៉ាងដូចម្តេច?',
  'how_to_reset_password_answer': 'នៅលើអេក្រង់ចូលប្រើ ចុច "ភ្លេចលេខសម្ងាត់"។ បញ្ចូលអ៊ីមែលដែលបានចុះឈ្មោះ ហើយយើងនឹងផ្ញើតំណកំណត់លេខសម្ងាត់ឡើងវិញទៅអ្នក។',
  'how_to_post_article': 'តើខ្ញុំប្រកាសអត្ថបទយ៉ាងដូចម្តេច?',
  'how_to_post_article_answer': 'រុករកទៅអេក្រង់ដើម ហើយចុចប៊ូតុង "+"។ ជ្រើសរើស "អត្ថបទ" ហើយបំពេញចំណងជើង មាតិកា និង ជ្រើសរើសប្រភេទ។ ចុច "ផ្សាយ" នៅពេលរួចរាល់។',
  'how_to_save_article': 'តើខ្ញុំរក្សាទុកអត្ថបទសម្រាប់ក្រោយយ៉ាងដូចម្តេច?',
  'how_to_save_article_answer': 'ចុចរូបតំណាងចំណាំនៅលើអត្ថបទណាមួយដើម្បីរក្សាទុក។ ចូលមើលអត្ថបទដែលបានរក្សាទុកទាំងអស់ពីផ្ទាំង "បានរក្សាទុក" នៅក្នុងការរុករកផ្នែកខាងក្រោម។',
  'how_to_report_content': 'តើខ្ញុំរាយការណ៍មាតិកាមិនសមរម្យយ៉ាងដូចម្តេច?',
  'how_to_report_content_answer': 'ចុចម៉ឺនុយបីចុចនៅលើការប្រកាសណាមួយ ហើយជ្រើសរើស "រាយការណ៍"។ ជ្រើសរើសមូលហេតុ ហើយដាក់ស្នើ។ ក្រុមរបស់យើងនឹងពិនិត្យវាក្នុងរយៈពេល ២៤ ម៉ោង។',
  'how_to_delete_account': 'តើខ្ញុំលុបគណនីរបស់ខ្ញុំយ៉ាងដូចម្តេច?',
  'how_to_delete_account_answer': 'ទៅកាន់ ប្រវត្តិរូប > ការកំណត់ភាពឯកជន > លុបគណនីរបស់ខ្ញុំ។ បញ្ជាក់ការសម្រេចចិត្តរបស់អ្នក។ ចំណាំ: សកម្មភាពនេះមានជាអចិន្ត្រៃយ៍ និង មិនអាចត្រឡប់ក្រោយវិញបានទេ។',

  // Change Password & Delete Account
  'current_password': 'លេខសម្ងាត់បច្ចុប្បន្ន',
  'new_password': 'លេខសម្ងាត់ថ្មី',
  'confirm_new_password': 'បញ្ជាក់លេខសម្ងាត់ថ្មី',
  'enter_password_to_confirm': 'បញ្ចូលលេខសម្ងាត់របស់អ្នកដើម្បីបញ្ជាក់',
  'please_enter_password': 'សូមបញ្ចូលលេខសម្ងាត់របស់អ្នក',
  'password_min_length': 'លេខសម្ងាត់ត្រូវតែមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
  'passwords_do_not_match': 'លេខសម្ងាត់មិនត្រូវគ្នា',

  'send': 'ផ្ញើ',
};
