const Map<String, String> kmKh = {
  // Settings
  'change_password_subtitle': 'ផ្លាស់ប្តូរលេខសម្ងាត់គណនីរបស់អ្នក',
  'change_password_coming_soon': 'មុខងារផ្លាស់ប្តូរលេខសម្ងាត់នឹងមកដល់ឆាប់ៗនេះ',
  'manage_your_privacy_settings': 'គ្រប់គ្រងការកំណត់ឯកជនភាពរបស់អ្នក',
  'privacy_settings_coming_soon': 'មុខងារការកំណត់ឯកជនភាពនឹងមកដល់ឆាប់ៗនេះ',
  'delete_account_subtitle': 'លុបគណនីរបស់អ្នកជាអចិន្ត្រៃយ៍',
  'delete_account_confirmation': 'តើអ្នកប្រាកដថាចង់លុបគណនីរបស់អ្នកមែនទេ? សកម្មភាពនេះមិនអាចត្រឡប់ក្រោយវិញបានទេ។',
  'account_deleted': 'គណនីត្រូវបានលុប',
  'account_deleted_message': 'គណនីរបស់អ្នកត្រូវបានលុប',
  'feature': 'មុខងារ',

  // Common
  'app_name': 'eNews',
  'welcome': 'សូមស្វាគមន៍',
  'email': 'អ៊ីមែល',
  'password': 'លេខសម្ងាត់',
  'login': 'ចូលប្រើ',
  'register': 'ចុះឈ្មោះ',
  'logout': 'ចាកចេញ',
  'save': 'រក្សាទុក',
  'cancel': 'បោះបង់',
  'delete': 'លុប',
  'edit': 'កែប្រែ',
  'search': 'ស្វែងរក',
  'settings': 'ការកំណត់',
  'preferences': 'ចំណូលចិត្ត',
  'push_notifications': 'ការជូនដំណឹងជាមួយនឹងការរំញោច',
  'receive_breaking_news': 'ទទួលបានការជូនដំណឹងពីព័ត៌មានថ្មីៗ',
  'email_notifications': 'ការជូនដំណឹងតាមអ៊ីមែល',
  'daily_news_digest': 'ការជូនដំណឹងប្រចាំថ្ងៃតាមអ៊ីមែល',
  'dark_mode': 'ទម្រង់ងងឹត',
  'enable_dark_theme': 'បើកប្រើប្រាស់ទម្រង់ងងឹត',
  'account': 'គណនី',
  'change_password': 'ប្ដូរលេខសម្ងាត់',
  'privacy_settings': 'ការកំណត់ភាពឯកជន',
  'delete_account': 'លុបគណនី',
  'profile': 'ប្រវត្តិរូប',
  'about': 'អំពី',
  'about_help': 'អំពី និង ជំនួយ',
  'refreshed': 'បានធ្វើបច្ចុប្បន្នភាព',
  'removed': 'បានលុប',

   //login
  'wellcome_back':'ស្វាគមន៍មកកាន់',
  'sign_in_to_continue':'ចូលប្រើដើម្បីបន្ត',

    //logout
  'create_account':'បង្កើតគណនី',
  'sign_up_to_get_started':'ចុះឈ្មោះដើម្បីចាប់ផ្តើម',

      //forgotpass
  'enter_your_email_address_and_we\'ll_send_you_a_link_to_reset_your_password':'បញ្ចូលអ៊ីមែលរបស់អ្នក ហើយយើងនឹងផ្ញើរលិខិតទៅកាន់អ្នកដើម្បីកំណត់លេខសម្ងាត់របស់អ្នក',
  'send_reset_link':'ផ្ញើរលិខិតកំណត់លេខសម្ងាត់',

  // Auth
  'login_title': 'ចូលប្រើគណនី',
  'register_title': 'បង្កើតគណនីថ្មី',
  'forgot_password': 'ភ្លេចលេខសម្ងាត់?',
  'dont_have_account': 'មិនទាន់មានគណនី?',
  'already_have_account': 'មានគណនីរួចហើយ?',
  'sign_in': 'ចូលប្រើ',
  'sign_up': 'ចុះឈ្មោះ',
  'name': 'ឈ្មោះពេញ',
  'confirm_password': 'បញ្ជាក់លេខសម្ងាត់',
  'welcome_back':'សូមស្វាគមន៍ត្រឡប់មកកាន់',
  'null':'',
  'password_must_be_at_least_6_characters': 'លេខសម្ងាត់ត្រូវតែមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
  'email_already_registered._please_login_instead.': 'អ៊ីមែលបានចុះឈ្មោះរួចហើយ។ សូមចូលប្រើវិញ។',
  'account_created_successfully!_please_login.': 'គណនីត្រូវបានបង្កើតដោយជោគជ័យ! សូមចូលប្រើ។',
  'name_must_be_at_least_3_characters': 'ឈ្មោះត្រូវតែមានយ៉ាងហោចណាស់ ៣ តួអក្សរ',
  'please_fill_in_all_fields': 'សូមបំពេញទាំងអស់',
  'please_enter_a_valid_email_address': 'សូមបញ្ចូលអ៊ីមែលដែលត្រឹមត្រូវ',
  'please_enter_your_email_and_password': 'សូមបញ្ចូលអ៊ីមែល និង លេខសម្ងាត់របស់អ្នក',
  'please_enter_your_email_address': 'សូមបញ្ចូលអ៊ីមែលរបស់អ្នក',
  'password_reset_link_sent_to_your_email': 'លិខិតកំណត់លេខសម្ងាត់ត្រូវបានផ្ញើទៅអ៊ីមែលរបស់អ្នក',
  'incorrect_password': 'លេខសម្ងាត់មិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។',
  'account_not_found': 'រកមិនឃើញគណនីទេ។ សូមចុះឈ្មោះជាមុន។',

  // Navigation
  'home': 'ទំព័រដើម',
  'category': 'ប្រភេទ',
  'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'saved': 'បានរក្សាទុក',

  // Dashboard
  'overview': 'ទិដ្ឋភាពទូទៅ',
  'views': 'ចំនួនមើល',
  'visits': 'ចំនួនចូលមើល',
  'new_users': 'អ្នកប្រើថ្មី',
  'active_users': 'អ្នកប្រើសកម្ម',
  'users': 'អ្នកប្រើ',
  'projects': 'គម្រោង',
  'operating_status': 'ស្ថានភាពប្រតិបត្តិការ',
  'device_traffic': 'ចរាចរឧបករណ៍', 
  'create_new_category': 'បង្កើតប្រភេទថ្មី',
  'admin':'Admin',
  'edit_category':'កែប្រែប្រភេទ',
  'delete_category':'លុបប្រភេទ',
  'media':'មេឌា',
  'color':'ពណ៌',
  'description':'ការពិពណ៌នា',
  'tag':'ស្លាក',
  'video':'វីដេអូ',
  'image':'រូបភាព',
  'delete_category_confirmation':'តើអ្នកប្រាកដថាចង់លុប',
  'create_post':'បង្កើតប្រកាស',
  'post':'ប្រកាស',
  'edit_info':'កែប្រែព័ត៌មាន',
  'change_cover':'ប្ដូរពណ៌ផ្ទាំង',
  'edit_cover':'កែប្រែពណ៌ផ្ទាំង',
  'title':'ចំណងជើង',
  'interested_headlines_for_more_people_to_see':'ចំណងជើងដែលគួរឱ្យចាប់អារម្មណ៍សម្រាប់មនុស្សច្រើនមើល',
  'topics':'ប្រធានបទ',
  'add':'បន្ថែម',

  //edit
  'post_updated_successfully' : 'ប្រកាសត្រូវបានកែប្រែដោយជោគជ័យ',
  'post_created_successfully' : 'ប្រកាសត្រូវបានបង្កើតដោយជោគជ័យ',
  'title_is_required' : 'ចំណងជើងត្រូវការជាអប្បបរមា',
  'enter_topic' : 'បញ្ចូលប្រធានបទ (ជាមួយ #)',
  'add_topic' : 'បន្ថែមប្រធានបទ',
  'topic' : 'ប្រធានបទ',

  // Home
  'following': 'កំពុងតាមដាន',
  'popular': 'ពេញនិយម',
  'news': 'ព័ត៌មាន',
  'sports': 'កីឡា',
  'entertainment': 'កម្សាន្ត',
  'technology': 'បច្ចេកវិទ្យា',
  'latest_posts': 'ប្រកាសថ្មីៗ',
  'see_all': 'មើលទាំងអស់',
  'like': 'ចូលចិត្ត',
  'comment': 'មតិយោបល់',
  'report': 'រាយការណ៍',
  'edit_this_post': 'កែប្រែប្រកាសនេះ',
  'add_to_favorite_list': 'បន្ថែមទៅបញ្ជីចូលចិត្ត',
  'remove_this_post_permanently': 'លុបប្រកាសនេះយ៉ាងស្ថាពរ',
  'report_inappropriate_content': 'រាយការណ៍មាតិកាដែលមិនសមរម្យ',
  'write_a_comment': 'សរសេរមតិយោបល់...',
  'share_video': 'ចែករំលែកវីដេអូ',
  'copy_link': 'ចម្លងតំណភ្ជាប់',
  'share_to_other_apps': 'ចែករំលែកទៅកម្មវិធីផ្សេងទៀត',
  'send_in_message': 'ផ្ញើក្នុងសារ',
  'just_now': 'ឥឡូវនេះ',

  // Profile
  'edit_profile': 'កែប្រវត្តិរូប',
  'my_bookmarks': 'កំណត់សម្គាល់របស់ខ្ញុំ',
  'notification': 'ការជូនដំណឹង',
  'setting': 'ការកំណត់',
  'logout_confirm': 'តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ?',
  'Logout': 'ចាកចេញ',
  'Cancel': 'បោះបង់',

  // Search
  'search_news': 'ស្វែងរកព័ត៌មាន...',
  'recent_searches': 'ការស្វែងរកថ្មីៗ',
  'trending_topics': 'ប្រធានបទពេញនិយម',
  'trending_videos': 'វីដេអូពេញនិយម',

  // Article
  'read_more': 'អានបន្ថែម',
  'min_read': 'នាទីអាន',
  'bookmark': 'រក្សាទុក',
  'share': 'ចែករំលែក',
  'bookmarks': 'ទុករក្សា',
  'no_bookmarks_yet': 'មិនទាន់មានការរក្សាទុក',
  'article_removed_from_bookmarks': 'លុបអត្ថបទចេញពីការរក្សាទុក',

  // Notifications
  'notifications': 'ការជូនដំណឹង',
  'mark_all_read': 'សម្គាល់ទាំងអស់ថាបានអាន',
  'no_notifications': 'គ្មានការជូនដំណឹង',

  // Language
  'select_language': 'ជ្រើសរើសភាសា',
  'english': 'English',
  'khmer': 'ភាសាខ្មែរ',

  // Errors
  'error': 'កំហុស',
  'success': 'ជោគជ័យ',
  'warning': 'ការព្រមាន',
  'info': 'ព័ត៌មាន',
  'invalid_email': 'អ៊ីមែលមិនត្រឹមត្រូវ',
  'invalid_password': 'លេខសម្ងាត់ត្រូវតែមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
  'passwords_dont_match': 'លេខសម្ងាត់មិនត្រូវគ្នា',
  'all_fields_required': 'ចាំបាច់បំពេញទាំងអស់',
  'login_failed': 'ការចូលប្រើបានបរាជ័យ។ សូមពិនិត្យមើលព័ត៌មានរបស់អ្នក',
  'registration_failed': 'ការចុះឈ្មោះបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត',
  'network_error': 'កំហុសបណ្តាញ។ សូមពិនិត្យការតភ្ជាប់របស់អ្នក',
};
